databases:
  - name: cesa_db
    plan: free
    databaseName: cesa_hukuk
    user: cesa_user

services:
  - type: web
    plan: starter
    name: cesa-hukuk
    runtime: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn CESA_Hukuk_Burosu.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cesa_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.7 