# Generated by Django 4.2.16 on 2025-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO için özel başlık (boş bırakılırsa kategori adı kullanılır)', max_length=200, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO için özel açıklama (boş bırakılırsa kategori açıklaması kullanılır)', null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO için özel başlık (boş bırakılırsa hizmet başlığı kullanılır)', max_length=200, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO için özel açıklama (boş bırakılırsa kısa açıklama kullanılır)', null=True, verbose_name='Meta Açıklama'),
        ),
    ]
