# Generated by Django 4.2.21 on 2025-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Ad Soyad"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "preferred_date",
                    models.DateField(verbose_name="Tercih Edilen Tarih"),
                ),
                ("preferred_time", models.TimeField(verbose_name="Tercih Edilen Saat")),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Mesaj"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("confirmed", "Onaylandı"),
                            ("cancelled", "İptal Edildi"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Randevu Talebi",
                "verbose_name_plural": "Randevu Talepleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Ad Soyad"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderim Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Lokasyon Adı")),
                ("address", models.TextField(verbose_name="Adres")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Google Maps Linki"
                    ),
                ),
                (
                    "google_maps_embed",
                    models.TextField(
                        blank=True, null=True, verbose_name="Google Maps Embed Kodu"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Ana Ofis"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofis Lokasyonu",
                "verbose_name_plural": "Ofis Lokasyonları",
                "ordering": ["order"],
            },
        ),
    ]
