# Generated by Django 4.2.16 on 2025-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
