# Generated by Django 4.2.10 on 2025-05-23 15:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='general/', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('google_analytics', models.TextField(blank=True, null=True, verbose_name='Google Analytics Kodu')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', tinymce.models.HTMLField(verbose_name='İçerik')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
            },
        ),
    ] 