# Generated by Django 4.2.21 on 2025-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Bu meta veri kümesinin adı (yönetim için)",
                        max_length=100,
                        verbose_name="Başlık",
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        help_text="Bu meta verilerin uygulanacağı URL (örn: /hizmetler/icra-hukuku/)",
                        max_length=255,
                        unique=True,
                        verbose_name="Hedef URL",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=200, verbose_name="Meta Başlık"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        help_text="160 karakteri geçmemelidir.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        help_text="Virgülle ayrılmış anahtar kelimeler.",
                        verbose_name="Meta Anahtar Kelimeler",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="OG Başlık"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, null=True, verbose_name="OG Açıklama"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Görsel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Yinelenen içerik için canonical URL belirtin (gerekirse).",
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "is_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Bu sayfa arama motorları tarafından indekslenmemeli mi?",
                        verbose_name="No Index",
                    ),
                ),
                (
                    "is_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="Bu sayfadaki bağlantılar takip edilmemeli mi?",
                        verbose_name="No Follow",
                    ),
                ),
                (
                    "schema_markup",
                    models.TextField(
                        blank=True,
                        help_text="Sayfa için özel JSON-LD schema markup.",
                        null=True,
                        verbose_name="Schema.org Markup",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Meta Verisi",
                "verbose_name_plural": "SEO Meta Verileri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="page",
            name="meta_keywords",
            field=models.TextField(
                blank=True,
                help_text="Virgülle ayrılmış anahtar kelimeler.",
                null=True,
                verbose_name="Meta Anahtar Kelimeler",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bing_site_verification",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Bing Site Doğrulama",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_founded",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Kuruluş Yılı"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_location_lat",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Enlem"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_location_long",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Boylam"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_opening_hours",
            field=models.TextField(
                blank=True,
                help_text="Örnek: Mo-Fr 09:00-18:00",
                null=True,
                verbose_name="Çalışma Saatleri",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_type",
            field=models.CharField(
                default="LegalService",
                help_text="Schema.org işletme türü, varsayılan: LegalService",
                max_length=100,
                verbose_name="İşletme Türü",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Google Site Doğrulama",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_author",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Meta Yazar"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_copyright",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Meta Telif Hakkı"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_keywords",
            field=models.TextField(
                blank=True,
                help_text="Virgülle ayrılmış anahtar kelimeler.",
                null=True,
                verbose_name="Meta Anahtar Kelimeler",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Sosyal medyada paylaşıldığında görünecek görsel. (1200x630px önerilir)",
                null=True,
                upload_to="general/",
                verbose_name="Sosyal Medya Paylaşım Görseli",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_locale",
            field=models.CharField(
                default="tr_TR", max_length=10, verbose_name="OG Dil"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_type",
            field=models.CharField(
                default="website", max_length=50, verbose_name="OG Türü"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="yandex_verification",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Yandex Doğrulama"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Ana sayfa için meta açıklama. 160 karakteri geçmemelidir.",
                null=True,
                verbose_name="Meta Açıklama",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Ana sayfa için meta başlık. Boş bırakılırsa site adı kullanılır.",
                max_length=200,
                null=True,
                verbose_name="Meta Başlık",
            ),
        ),
    ]
