# Generated by Django 4.2.21 on 2025-06-08 15:21

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yazar",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(
                help_text="Makalenin tam içeriği", verbose_name="İçerik"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Ana sayfada öne çıkarılsın mı?",
                verbose_name="Öne Çıkan",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="JPG, PNG formatında, maksimum 10MB. Önerilen boyut: 1200x630px",
                null=True,
                upload_to=apps.blog.models.article_image_upload,
                validators=[apps.blog.models.validate_article_image_size],
                verbose_name="Kapak Görseli",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Otomatik oluşturulur",
                max_length=220,
                unique=True,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Makalenin kısa özeti (SEO için önemli)",
                max_length=300,
                null=True,
                verbose_name="Özet",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                help_text="Makalenin başlığını yazın",
                max_length=200,
                verbose_name="Başlık",
            ),
        ),
    ]
