# Generated by Django 4.2.21 on 2025-07-16 12:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Makalenin tam içeriği", verbose_name="İçerik"
            ),
        ),
    ]
