# Generated by Django 4.2.21 on 2025-07-16 13:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Makalenin tam içeriği", verbose_name="İçerik"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Makalenin kısa özeti - Zengin metin formatı desteklenir",
                null=True,
                verbose_name="Özet",
            ),
        ),
    ]
