# Generated by Django 4.2.21 on 2025-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Örn: Av., Dr., Prof. Dr.",
                        max_length=50,
                        verbose_name="Unvan",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Erkek"), ("F", "Kadın")],
                        max_length=1,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lawyers/",
                        verbose_name="Fotoğraf",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Örn: Kurucu Ortak, Kıdemli Avukat, Stajyer Avukat",
                        max_length=100,
                        verbose_name="Pozisyon",
                    ),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Eğitim"),
                ),
                (
                    "experience",
                    models.TextField(blank=True, null=True, verbose_name="Deneyim"),
                ),
                (
                    "expertise_areas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Uzmanlık Alanları"
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Yabancı Diller",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Avukatların görüntülenme sırası",
                        verbose_name="Sıralama",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avukat",
                "verbose_name_plural": "Avukatlar",
                "ordering": ["order", "last_name"],
            },
        ),
    ]
