# Generated by Django 4.2.21 on 2025-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Uzmanlık Alanı"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzmanlık Alanı",
                "verbose_name_plural": "Uzmanlık Alanları",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="lawyer",
            name="short_bio",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Kısa Biyografi"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="expertise_areas",
            field=models.TextField(
                blank=True,
                help_text="Yukarıdaki uzmanlık alanlarına ek olarak",
                null=True,
                verbose_name="Diğer Uzmanlık Alanları",
            ),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                to="lawyers.specialization",
                verbose_name="Uzmanlık Alanları",
            ),
        ),
    ]
