# Generated by Django 4.2.21 on 2025-06-08 15:05

import apps.lawyers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0002_specialization_lawyer_short_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Avukatların görüntülenme sırası (0=en üstte)",
                verbose_name="Sıralama",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="JPG, PNG formatında, maksimum 5MB",
                null=True,
                upload_to=apps.lawyers.models.lawyer_photo_upload,
                validators=[apps.lawyers.models.validate_image_size],
                verbose_name="Fotoğraf",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="short_bio",
            field=models.TextField(
                blank=True,
                help_text="Maksimum 200 karakter",
                max_length=200,
                null=True,
                verbose_name="Kısa Biyografi",
            ),
        ),
    ]
