# Generated by Django 4.2.21 on 2025-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0003_alter_lawyer_order_alter_lawyer_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="expertise_areas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Diğer Uzmanlık Alanları"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="lawyers/", verbose_name="Fotoğraf"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="position",
            field=models.CharField(
                default="Avukat", max_length=100, verbose_name="Pozisyon"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="short_bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Kısa Biyografi"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="title",
            field=models.CharField(
                default="Av.",
                help_text="Örn: Av., Dr., Prof. Dr.",
                max_length=50,
                verbose_name="Unvan",
            ),
        ),
    ]
