# Generated by Django 4.2.21 on 2025-06-08 15:41

import apps.lawyers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0004_alter_lawyer_expertise_areas_alter_lawyer_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="expertise_areas",
            field=models.TextField(
                blank=True,
                help_text="Yukarıdaki uzmanlık alanlarına ek olarak",
                null=True,
                verbose_name="Diğer Uzmanlık Alanları",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Avukatların görüntülenme sırası (0=en üstte)",
                verbose_name="Sıralama",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="JPG, PNG formatında, maksimum 5MB",
                null=True,
                upload_to=apps.lawyers.models.lawyer_photo_upload,
                verbose_name="Fotoğraf",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="position",
            field=models.CharField(
                default="Avukat",
                help_text="Örn: Kurucu Ortak, Kıdemli Avukat, Stajyer Avukat",
                max_length=100,
                verbose_name="Pozisyon",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="short_bio",
            field=models.TextField(
                blank=True,
                help_text="Maksimum 200 karakter",
                max_length=200,
                null=True,
                verbose_name="Kısa Biyografi",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="temp-slug",
                max_length=200,
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
